name: flussie
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  get:
  get_storage: 
  http: 
  intl:
  flutter_map:
  latlong2:
  url_launcher:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/json/battery_health.json
    - assets/json/charges_all.json
    - assets/json/charges_suc_only.json
    - assets/json/drives.json
    - assets/json/location.json
    - assets/json/path_1753682464.json
    - assets/json/path_1755152200.json
    - assets/json/path_1755331023.json
    - assets/json/path_1776870163.json
    - assets/json/path_1776952931.json
    - assets/json/vehicle.json
    - assets/json/vehicles.json
    - assets/images/map.png
